version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    #  python: 3.7
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - node --version
      - python --version
      - aws --version
      - sam --version
      #- pip install --user aws-sam-cli
      #- USER_BASE_PATH=$(python -m site --user-base)
      - pip install aws-sam-cli
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - npm install 
  pre_build:
    commands:
      - echo '========================================='
      - echo '==  pre_build'
      - echo '========================================='
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build

  post_build:
    commands:
      - echo '========================================='
      - echo '==  post_build'
      - echo '========================================='
      - npm run test
      - npm run coverage
      #- npm run sonar-scanner
      - aws cloudformation package --template-file template.yml --s3-bucket itg-bucket-one --output-template-file package.yml

artifacts:
  type: zip
  files: 
    - buildspec.yml
    - template.yml
    - package.yml
