version: 0.1
phases:
  install:
    commands:
      - npm install 
      - aws cloudformation package --template-file template.yml --s3-bucket itg-bucket-one --output-template-file package.yml
    artifacts:
      type: zip
      files: 
        - template.yml
        - package.yml
